# Generated by Django 5.0.3 on 2024-06-28 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('beneficiary_id', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('oxygen_count', models.FloatField()),
                ('temperature', models.FloatField()),
                ('pulse_rate', models.FloatField()),
                ('diabetic_value', models.FloatField()),
                ('systolic', models.FloatField()),
                ('diastolic', models.FloatField()),
                ('capture_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('occupation', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('bmi', models.FloatField()),
                ('bp_value', models.CharField(max_length=20)),
                ('diabetes', models.CharField(max_length=10)),
                ('energy_levels', models.CharField(max_length=20)),
                ('sleep_issues', models.CharField(max_length=20)),
                ('diet', models.CharField(max_length=100)),
                ('physical_activity_level', models.CharField(max_length=20)),
                ('smoking_alcohol', models.CharField(max_length=20)),
                ('mental_health', models.CharField(max_length=20)),
                ('symptoms', models.JSONField()),
                ('family_history', models.TextField()),
                ('diagnosis_conditions', models.TextField()),
                ('ayush_practices', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField()),
                ('predicted_bmi', models.FloatField()),
                ('predicted_diabetic_value', models.FloatField()),
                ('predicted_systolic', models.FloatField()),
                ('predicted_diastolic', models.FloatField()),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RiskEvaluation.beneficiary')),
            ],
        ),
    ]
