"""
URL configuration for AutoGenerated project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static 
from django.conf import settings
urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('Auto_Ques_and_Ans.urls')),
    path('risk',include('patient_risk.urls')),
    path('consultation/',include('consultation.urls')),
    path('consultation_app/',include('consultation_app.urls')),
    path('MedicalBot/',include('ChatBot.urls')),
    path('speech_processing/',include('speech_processsing.urls')),
    path('RiskEvaluation/',include('RiskEvaluation.urls')),
    path('MedicalDocumentExtraction/',include('MedicalDocumentExtraction.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)