name: Run Django Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-and-run:
    runs-on: ubuntu-latest # Use GitHub-hosted runner with Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            portaudio19-dev \
            libsndfile1  # These packages are required to build PyAudio

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install Python packages

      - name: Set up database
        run: |
          sudo apt-get install -y postgresql postgresql-contrib
          sudo service postgresql start
          sudo -u postgres psql -c "CREATE DATABASE mydb;"

      - name: Run Django migrations and collect static files
        run: |
          python manage.py migrate
          python manage.py collectstatic --noinput

      - name: Run Django server
        run: |
          python manage.py runserver 0.0.0.0:8000
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DJANGO_DEBUG: "True"
